"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, AlertTriangle, CheckCircle } from "lucide-react";

type SectionBlock =
  | { type: "para"; text: string }
  | { type: "warning"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "provides"; label: string; items: string[] };

const sections: { id: string; title: string; blocks: SectionBlock[] }[] = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    blocks: [
      { type: "para", text: "By creating an account on Athlixir, you confirm that:" },
      {
        type: "bullets",
        items: [
          "The information provided by you is true, accurate, and up to date.",
          "You will not upload fake certificates, medical records, or performance data.",
          "You agree to follow the Athlixir platform guidelines and policies.",
        ],
      },
      {
        type: "warning",
        text: "If a user enters false, misleading, or fake information, Athlixir will not be responsible for any consequences, decisions, or opportunities lost due to that incorrect data.",
      },
      { type: "para", text: "Athlixir reserves the right to verify, suspend, or permanently remove accounts that violate these terms." },
    ],
  },
  {
    id: "analytics",
    title: "2. Performance Analytics Consent",
    blocks: [
      { type: "para", text: "Athlixir collects training and performance data to support athlete development." },
      { type: "para", text: "By enabling this option, you agree that:" },
      {
        type: "bullets",
        items: [
          "Your training and performance data may be analyzed using AI systems.",
          "Data from manual entries, competitions, or wearable devices may be used to generate insights.",
          "Coaches, trainers, or authorized experts may view performance analytics to provide guidance.",
        ],
      },
      {
        type: "provides",
        label: "This allows Athlixir to provide:",
        items: ["Performance tracking", "Injury prediction insights", "Training improvement recommendations"],
      },
      {
        type: "warning",
        text: "Athlixir is not responsible for inaccurate analysis caused by incorrect or incomplete data entered by the user.",
      },
    ],
  },
  {
    id: "wearable",
    title: "3. Wearable & Sensor Data Consent",
    blocks: [
      { type: "para", text: "If you connect or use Athlixir-supported wearable devices, you consent that:" },
      {
        type: "bullets",
        items: [
          "Sensor data such as movement, speed, activity metrics, and training patterns may be collected.",
          "This data may be used to analyze training performance and injury risks.",
          "Data will be stored securely and used only for athletic development and analytics purposes.",
        ],
      },
      {
        type: "warning",
        text: "Athlixir is not responsible for device malfunctions or incorrect data generated by third-party devices.",
      },
    ],
  },
  {
    id: "research",
    title: "4. Data Usage for Research",
    blocks: [
      { type: "para", text: "Athlixir aims to improve sports technology, performance analytics, and athlete development research." },
      { type: "para", text: "By allowing research usage:" },
      {
        type: "bullets",
        items: [
          "Your anonymized (non-identifiable) data may be used for research and platform improvement.",
          "Personal identity details will never be publicly disclosed without permission.",
        ],
      },
      {
        type: "provides",
        label: "Data may be used to improve AI models for:",
        items: ["Injury prediction", "Performance analytics", "Athlete development research"],
      },
    ],
  },
  {
    id: "privacy",
    title: "5. Privacy & Data Security",
    blocks: [
      { type: "para", text: "Athlixir ensures:" },
      {
        type: "bullets",
        items: [
          "Secure storage of personal, performance, and medical data.",
          "Restricted access to sensitive records.",
          "Use of encryption and industry-standard security measures to protect athlete information.",
        ],
      },
    ],
  },
  {
    id: "responsibility",
    title: "6. Platform Responsibility",
    blocks: [
      { type: "para", text: "Athlixir provides analytics, insights, and recommendations for guidance only." },
      { type: "para", text: "Athlixir is not responsible for:" },
      {
        type: "bullets",
        items: [
          "Medical decisions taken without consulting qualified professionals.",
          "Incorrect manual data entered by users.",
          "Fake documents or certificates uploaded by users.",
          "Decisions made by coaches, academies, selectors, or institutions based on platform data.",
        ],
      },
    ],
  },
  {
    id: "rights",
    title: "7. User Rights",
    blocks: [
      { type: "para", text: "Users have the right to:" },
      {
        type: "bullets",
        items: [
          "Access their personal data.",
          "Update or edit their profile information.",
          "Request account deletion and removal of stored data.",
        ],
      },
    ],
  },
];

const consentItems = [
  "I agree to the Athlixir Terms & Conditions",
  "I allow Athlixir to analyze my performance data",
  "I allow anonymized data usage for research and development",
];

export default function TermsPage() {
  const [consents, setConsents] = useState([false, false, false]);
  const allChecked = consents.every(Boolean);

  return (
    <div style={{ background: "var(--color-background)", minHeight: "100vh" }}>

      {/* Top nav bar */}
      <header style={{
        borderBottom: "1px solid var(--border-color-neutral)",
        background: "var(--color-surface-1)",
        position: "sticky",
        top: 0,
        zIndex: 40,
      }}>
        <div className="container" style={{ display: "flex", alignItems: "center", justifyContent: "space-between", height: "var(--navbar-height)" }}>
          {/* Logo */}
          <Link href="/" style={{ display: "flex", alignItems: "center", gap: "var(--space-2)", textDecoration: "none" }}>
            <svg width="28" height="28" viewBox="0 0 52 52">
              <polygon points="26,4 6,48 14,48 26,18" fill="#F97316" />
              <polygon points="26,4 46,48 38,48 26,18" fill="#EA580C" />
              <rect x="14" y="30" width="24" height="5" rx="1" fill="#F97316" />
            </svg>
            <span style={{ fontWeight: "var(--fw-bold)", fontSize: "var(--fs-h4)", color: "var(--color-text-primary)" }}>Athlixir</span>
          </Link>

          {/* Back link */}
          <Link
            href="/onboarding"
            style={{
              display: "flex",
              alignItems: "center",
              gap: "var(--space-1)",
              fontSize: "var(--fs-body-sm)",
              fontWeight: "var(--fw-medium)",
              color: "var(--color-text-secondary)",
              textDecoration: "none",
              transition: "color var(--transition-fast)",
            }}
            onMouseEnter={e => (e.currentTarget.style.color = "var(--color-text-primary)")}
            onMouseLeave={e => (e.currentTarget.style.color = "var(--color-text-secondary)")}
          >
            <ArrowLeft size={16} />
            Back
          </Link>
        </div>
      </header>

      <main className="container" style={{ paddingTop: "var(--space-6)", paddingBottom: "var(--space-10)" }}>

        {/* Page header */}
        <div style={{ maxWidth: "720px", marginBottom: "var(--space-6)" }}>
          <h1 style={{
            fontSize: "var(--fs-hero-l)",
            fontWeight: "var(--fw-bold)",
            lineHeight: "var(--lh-tight)",
            letterSpacing: "var(--ls-hero)",
            color: "var(--color-text-primary)",
            marginBottom: "var(--space-2)",
          }}>
            Terms &amp; <span className="text-gradient">Consent</span>
          </h1>

          <p style={{ fontSize: "var(--fs-body)", color: "var(--color-text-secondary)", lineHeight: "var(--lh-body)" }}>
            Please read the following terms carefully. Your registration on Athlixir constitutes full acceptance of these terms and consent declarations.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>

            {sections.map((section) => (
              <section
                key={section.id}
                id={section.id}
                className="card"
                style={{ scrollMarginTop: "calc(var(--navbar-height) + var(--space-4))" }}
              >
                <h2 style={{
                  fontSize: "var(--fs-h4)",
                  fontWeight: "var(--fw-semibold)",
                  color: "var(--color-text-primary)",
                  marginBottom: "var(--space-2)",
                  paddingBottom: "var(--space-1)",
                  borderBottom: "1px solid var(--border-color-neutral)",
                }}>
                  {section.title}
                </h2>

                <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-2)" }}>
                  {section.blocks.map((block, i) => {
                    if (block.type === "para") {
                      return (
                        <p key={i} style={{ fontSize: "var(--fs-body-md)", color: "var(--color-text-secondary)", lineHeight: "var(--lh-body)" }}>
                          {block.text}
                        </p>
                      );
                    }
                    if (block.type === "warning") {
                      return (
                        <div key={i} className="alert alert-warning" style={{ borderRadius: "var(--radius-md)" }}>
                          <AlertTriangle size={16} style={{ flexShrink: 0, marginTop: "2px" }} />
                          <span style={{ fontSize: "var(--fs-body-sm)", lineHeight: "var(--lh-body)" }}>
                            <strong style={{ color: "var(--color-text-primary)" }}>Note: </strong>
                            <span style={{ color: "var(--color-text-primary)", fontWeight: "var(--fw-normal)" }}>{block.text}</span>
                          </span>
                        </div>
                      );
                    }
                    if (block.type === "bullets") {
                      return (
                        <ul key={i} style={{ display: "flex", flexDirection: "column", gap: "var(--space-1)", paddingLeft: 0, margin: 0, listStyle: "none" }}>
                          {block.items.map((item, j) => (
                            <li key={j} style={{ display: "flex", alignItems: "flex-start", gap: "var(--space-1)" }}>
                              <CheckCircle size={14} style={{ color: "var(--color-primary)", marginTop: "3px", flexShrink: 0 }} />
                              <span style={{ fontSize: "var(--fs-body-sm)", color: "var(--color-text-secondary)", lineHeight: "var(--lh-body)" }}>{item}</span>
                            </li>
                          ))}
                        </ul>
                      );
                    }
                    if (block.type === "provides") {
                      return (
                        <div key={i} style={{
                          background: "var(--color-surface-2)",
                          border: "1px solid var(--border-color-neutral)",
                          borderRadius: "var(--radius-md)",
                          padding: "var(--space-2) var(--space-3)",
                        }}>
                          <p style={{ fontSize: "var(--fs-body-sm)", color: "var(--color-text-muted)", marginBottom: "var(--space-1)" }}>
                            {block.label}
                          </p>
                          <ul style={{ display: "flex", flexDirection: "column", gap: "var(--space-0-5)", paddingLeft: 0, margin: 0, listStyle: "none" }}>
                            {block.items.map((item, j) => (
                              <li key={j} style={{ display: "flex", alignItems: "center", gap: "var(--space-1)" }}>
                                <span style={{
                                  width: "6px",
                                  height: "6px",
                                  borderRadius: "var(--radius-full)",
                                  background: "var(--color-primary)",
                                  flexShrink: 0,
                                  display: "inline-block",
                                }} />
                                <span style={{ fontSize: "var(--fs-body-sm)", color: "var(--color-text-secondary)", lineHeight: "var(--lh-body)" }}>{item}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      );
                    }
                    return null;
                  })}
                </div>
              </section>
            ))}

            {/* Section 8 — Consent Confirmation */}
            <section
              id="consent"
              className="card-feature"
              style={{ scrollMarginTop: "calc(var(--navbar-height) + var(--space-4))" }}
            >
              <h2 style={{ fontSize: "var(--fs-h4)", fontWeight: "var(--fw-semibold)", color: "var(--color-text-primary)", marginBottom: "var(--space-3)" }}>
                8. Consent Confirmation
              </h2>

              <p style={{ fontSize: "var(--fs-body-md)", color: "var(--color-text-secondary)", lineHeight: "var(--lh-body)", marginBottom: "var(--space-3)" }}>
                Before completing registration, the user must confirm all of the following:
              </p>

              <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-2)", marginBottom: "var(--space-4)" }}>
                {consentItems.map((item, i) => (
                  <label
                    key={i}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "var(--space-2)",
                      padding: "var(--space-2) var(--space-3)",
                      background: consents[i] ? "rgba(249,115,22,0.07)" : "var(--color-surface-2)",
                      border: `1px solid ${consents[i] ? "var(--color-primary)" : "var(--border-color-neutral)"}`,
                      borderRadius: "var(--radius-md)",
                      cursor: "pointer",
                      transition: "background var(--transition-hover), border-color var(--transition-hover)",
                    }}
                  >
                    <input
                      type="checkbox"
                      className="form-checkbox"
                      checked={consents[i]}
                      onChange={(e) =>
                        setConsents((prev) => prev.map((v, idx) => (idx === i ? e.target.checked : v)))
                      }
                      style={{ flexShrink: 0 }}
                    />
                    <span style={{ fontSize: "var(--fs-body-sm)", color: "var(--color-text-primary)", fontWeight: "var(--fw-medium)", userSelect: "none" }}>
                      {item}
                    </span>
                  </label>
                ))}
              </div>

              <div style={{ display: "flex", justifyContent: "flex-end" }}>
                {allChecked ? (
                  <Link href="/dashboard" className="btn btn-primary btn-md btn-pill">
                    Create Account
                  </Link>
                ) : (
                  <button
                    disabled
                    className="btn btn-primary btn-md btn-pill"
                    style={{ opacity: 0.4, cursor: "not-allowed" }}
                    title="Please accept all terms to continue"
                  >
                    Create Account
                  </button>
                )}
              </div>
            </section>

        </div>
      </main>

    </div>
  );
}
