"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { ArrowLeft, AlertTriangle, CheckCircle, ShieldCheck, TriangleAlert, X } from "lucide-react";

type SectionBlock =
  | { type: "para"; text: string }
  | { type: "warning"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "provides"; label: string; items: string[] };

const sections: { id: string; title: string; blocks: SectionBlock[] }[] = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    blocks: [
      { type: "para", text: "By creating an account on Athlixir, you confirm that:" },
      {
        type: "bullets",
        items: [
          "The information provided by you is true, accurate, and up to date.",
          "You will not upload fake certificates, medical records, or performance data.",
          "You agree to follow the Athlixir platform guidelines and policies.",
        ],
      },
      {
        type: "warning",
        text: "If a user enters false, misleading, or fake information, Athlixir will not be responsible for any consequences, decisions, or opportunities lost due to that incorrect data.",
      },
      { type: "para", text: "Athlixir reserves the right to verify, suspend, or permanently remove accounts that violate these terms." },
    ],
  },
  {
    id: "analytics",
    title: "2. Performance Analytics Consent",
    blocks: [
      { type: "para", text: "Athlixir collects training and performance data to support athlete development." },
      { type: "para", text: "By enabling this option, you agree that:" },
      {
        type: "bullets",
        items: [
          "Your training and performance data may be analyzed using AI systems.",
          "Data from manual entries, competitions, or wearable devices may be used to generate insights.",
          "Coaches, trainers, or authorized experts may view performance analytics to provide guidance.",
        ],
      },
      {
        type: "provides",
        label: "This allows Athlixir to provide:",
        items: ["Performance tracking", "Injury prediction insights", "Training improvement recommendations"],
      },
      {
        type: "warning",
        text: "Athlixir is not responsible for inaccurate analysis caused by incorrect or incomplete data entered by the user.",
      },
    ],
  },
  {
    id: "wearable",
    title: "3. Wearable & Sensor Data Consent",
    blocks: [
      { type: "para", text: "If you connect or use Athlixir-supported wearable devices, you consent that:" },
      {
        type: "bullets",
        items: [
          "Sensor data such as movement, speed, activity metrics, and training patterns may be collected.",
          "This data may be used to analyze training performance and injury risks.",
          "Data will be stored securely and used only for athletic development and analytics purposes.",
        ],
      },
      {
        type: "warning",
        text: "Athlixir is not responsible for device malfunctions or incorrect data generated by third-party devices.",
      },
    ],
  },
  {
    id: "research",
    title: "4. Data Usage for Research",
    blocks: [
      { type: "para", text: "Athlixir aims to improve sports technology, performance analytics, and athlete development research." },
      { type: "para", text: "By allowing research usage:" },
      {
        type: "bullets",
        items: [
          "Your anonymized (non-identifiable) data may be used for research and platform improvement.",
          "Personal identity details will never be publicly disclosed without permission.",
        ],
      },
      {
        type: "provides",
        label: "Data may be used to improve AI models for:",
        items: ["Injury prediction", "Performance analytics", "Athlete development research"],
      },
    ],
  },
  {
    id: "privacy",
    title: "5. Privacy & Data Security",
    blocks: [
      { type: "para", text: "Athlixir ensures:" },
      {
        type: "bullets",
        items: [
          "Secure storage of personal, performance, and medical data.",
          "Restricted access to sensitive records.",
          "Use of encryption and industry-standard security measures to protect athlete information.",
        ],
      },
    ],
  },
  {
    id: "responsibility",
    title: "6. Platform Responsibility",
    blocks: [
      { type: "para", text: "Athlixir provides analytics, insights, and recommendations for guidance only." },
      { type: "para", text: "Athlixir is not responsible for:" },
      {
        type: "bullets",
        items: [
          "Medical decisions taken without consulting qualified professionals.",
          "Incorrect manual data entered by users.",
          "Fake documents or certificates uploaded by users.",
          "Decisions made by coaches, academies, selectors, or institutions based on platform data.",
        ],
      },
    ],
  },
  {
    id: "rights",
    title: "7. User Rights",
    blocks: [
      { type: "para", text: "Users have the right to:" },
      {
        type: "bullets",
        items: [
          "Access their personal data.",
          "Update or edit their profile information.",
          "Request account deletion and removal of stored data.",
        ],
      },
    ],
  },
];

const consentItems = [
  "I agree to the Athlixir Terms & Conditions",
  "I allow Athlixir to analyze my performance data",
  "I allow anonymized data usage for research and development",
];

export default function TermsPage() {
  const [consents, setConsents] = useState([false, false, false]);
  const [showWarning, setShowWarning] = useState(true);
  const allChecked = consents.every(Boolean);

  // Lock body scroll while warning is open
  useEffect(() => {
    if (showWarning) document.body.style.overflow = "hidden";
    else document.body.style.overflow = "";
    return () => { document.body.style.overflow = ""; };
  }, [showWarning]);

  return (
    <div className="min-h-screen bg-[#050505]">

      {/* Read carefully warning popup */}
      {showWarning && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm px-5">
          <div className="bg-[#121212] border border-[#FF5722]/40 rounded-xl p-7 max-w-md w-full shadow-2xl">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-[#FF5722]/15 flex items-center justify-center shrink-0">
                <TriangleAlert size={20} className="text-[#FF5722]" />
              </div>
              <h2 className="text-base font-black text-white uppercase tracking-widest">Read Carefully</h2>
            </div>
            <p className="text-sm text-white/60 leading-relaxed mb-2">
              You are about to review the <span className="text-white font-semibold">Terms &amp; Consent</span> for Athlixir.
            </p>
            <p className="text-sm text-white/60 leading-relaxed mb-6">
              By accepting these terms, you confirm that all information provided is <span className="text-[#FF5722] font-semibold">true and accurate</span>. Athlixir will not be responsible for any consequences arising from false or misleading data.
            </p>
            <div className="flex items-center gap-2 bg-amber-500/10 border border-amber-500/20 rounded-md px-4 py-3 mb-6">
              <AlertTriangle size={14} className="text-amber-400 shrink-0" />
              <p className="text-xs text-amber-300 leading-relaxed">
                Please read each section thoroughly before checking the consent boxes.
              </p>
            </div>
            <button
              onClick={() => setShowWarning(false)}
              className="w-full py-3 bg-[#FF5722] hover:bg-[#E64A19] text-white font-black text-[11px] uppercase tracking-widest rounded-md transition-all"
            >
              I Understand — Continue
            </button>
          </div>
        </div>
      )}

      {/* Sticky header */}
      <header className="sticky top-0 z-40 bg-[#0f0f0f] border-b border-white/10">
        <div className="max-w-4xl mx-auto px-5 flex items-center justify-between h-16">
          <Link href="/" className="flex items-center gap-2 no-underline">
            <svg width="26" height="26" viewBox="0 0 52 52">
              <polygon points="26,4 6,48 14,48 26,18" fill="#FF5722" />
              <polygon points="26,4 46,48 38,48 26,18" fill="#E64A19" />
              <rect x="14" y="30" width="24" height="5" rx="1" fill="#FF5722" />
            </svg>
            <span className="font-bold text-lg text-white tracking-tight">Athlixir</span>
          </Link>

          <Link
            href="/onboarding"
            className="flex items-center gap-1.5 text-sm text-white/50 hover:text-white transition-colors no-underline"
          >
            <ArrowLeft size={15} />
            Back
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-5 py-10">

        {/* Page title */}
        <div className="mb-8">
          <h1 className="text-4xl font-black text-white tracking-tight mb-2">
            Terms &amp;{" "}
            <span className="text-[#FF5722]">Consent</span>
          </h1>
          <p className="text-white/50 text-sm leading-relaxed max-w-2xl">
            Please read the following terms carefully. Your registration on Athlixir constitutes full acceptance of these terms and consent declarations.
          </p>
        </div>

        {/* Term sections */}
        <div className="flex flex-col gap-4">
          {sections.map((section) => (
            <section
              key={section.id}
              id={section.id}
              className="bg-white/5 border border-white/10 rounded-xl p-6"
              style={{ scrollMarginTop: "80px" }}
            >
              <h2 className="text-base font-semibold text-white mb-4 pb-3 border-b border-white/10">
                {section.title}
              </h2>

              <div className="flex flex-col gap-3">
                {section.blocks.map((block, i) => {
                  if (block.type === "para") {
                    return (
                      <p key={i} className="text-sm text-white/60 leading-relaxed">
                        {block.text}
                      </p>
                    );
                  }

                  if (block.type === "warning") {
                    return (
                      <div key={i} className="flex gap-3 bg-amber-500/10 border border-amber-500/20 rounded-md px-4 py-3">
                        <AlertTriangle size={15} className="text-amber-400 mt-0.5 shrink-0" />
                        <p className="text-sm text-white/80 leading-relaxed">
                          <span className="font-semibold text-amber-400">Note: </span>
                          {block.text}
                        </p>
                      </div>
                    );
                  }

                  if (block.type === "bullets") {
                    return (
                      <ul key={i} className="flex flex-col gap-2 m-0 p-0 list-none">
                        {block.items.map((item, j) => (
                          <li key={j} className="flex items-start gap-2">
                            <CheckCircle size={13} className="text-[#FF5722] mt-0.5 shrink-0" />
                            <span className="text-sm text-white/60 leading-relaxed">{item}</span>
                          </li>
                        ))}
                      </ul>
                    );
                  }

                  if (block.type === "provides") {
                    return (
                      <div key={i} className="bg-white/5 border border-white/10 rounded-md px-4 py-3">
                        <p className="text-xs text-white/40 uppercase tracking-widest font-semibold mb-2">
                          {block.label}
                        </p>
                        <ul className="flex flex-col gap-1.5 m-0 p-0 list-none">
                          {block.items.map((item, j) => (
                            <li key={j} className="flex items-center gap-2">
                              <span className="w-1.5 h-1.5 rounded-full bg-[#FF5722] shrink-0" />
                              <span className="text-sm text-white/60">{item}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    );
                  }

                  return null;
                })}
              </div>
            </section>
          ))}

          {/* 8. Consent Confirmation */}
          <section
            id="consent"
            className="bg-white/5 border border-[#FF5722]/30 rounded-xl p-6"
            style={{ scrollMarginTop: "80px" }}
          >
            <div className="flex items-center gap-2 mb-1">
              <ShieldCheck size={18} className="text-[#FF5722]" />
              <h2 className="text-base font-semibold text-white">8. Consent Confirmation</h2>
            </div>
            <p className="text-sm text-white/50 leading-relaxed mb-5">
              Before completing registration, please confirm all of the following:
            </p>

            <div className="flex flex-col gap-3 mb-6">
              {consentItems.map((item, i) => (
                <label
                  key={i}
                  className={`flex items-center gap-3 px-4 py-3 rounded-md border cursor-pointer transition-all select-none ${
                    consents[i]
                      ? "bg-[#FF5722]/10 border-[#FF5722]/40"
                      : "bg-white/5 border-white/10 hover:bg-white/8 hover:border-white/20"
                  }`}
                >
                  <input
                    type="checkbox"
                    checked={consents[i]}
                    onChange={(e) =>
                      setConsents((prev) => prev.map((v, idx) => (idx === i ? e.target.checked : v)))
                    }
                    className="w-4 h-4 rounded accent-[#FF5722] cursor-pointer shrink-0"
                  />
                  <span className="text-sm text-white font-medium">{item}</span>
                </label>
              ))}
            </div>

            <div className="flex justify-end">
              {allChecked ? (
                <Link
                  href="/dashboard"
                  onClick={() => sessionStorage.removeItem("athlixir_onboarding_draft")}
                  className="px-8 py-3 bg-[#FF5722] hover:bg-[#E64A19] text-white font-black rounded-md text-[11px] uppercase tracking-widest transition-all no-underline"
                >
                  Create Account
                </Link>
              ) : (
                <button
                  disabled
                  className="px-8 py-3 bg-[#FF5722] text-white font-black rounded-md text-[11px] uppercase tracking-widest opacity-30 cursor-not-allowed"
                  title="Please accept all terms to continue"
                >
                  Create Account
                </button>
              )}
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
